# Generated by Django 2.1.2 on 2018-10-14 07:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('description', models.CharField(max_length=255, verbose_name='Item Description')),
                ('start_time', models.DateTimeField(blank=True, verbose_name='Auction Starts At')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='Auction Ends At')),
                ('starting_amount', models.FloatField(default=0.0, verbose_name='Starting Amount')),
                ('image_url', models.TextField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biddings.AuctionItem')),
            ],
        ),
    ]
