# Generated by Django 2.1.2 on 2018-10-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biddings', '0002_auto_20181014_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='status',
            field=models.CharField(default='upcoming', max_length=40, verbose_name='Auction Status'),
        ),
    ]
