# Generated by Django 2.1.2 on 2018-10-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biddings', '0004_auctionitem_final_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='final_amount',
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Item Name'),
        ),
    ]
