# Generated by Django 2.1.2 on 2018-10-16 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biddings', '0005_auto_20181015_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionitem',
            options={'verbose_name': 'auction item', 'verbose_name_plural': 'auction items'},
        ),
        migrations.AlterModelOptions(
            name='bids',
            options={'verbose_name': 'bid', 'verbose_name_plural': 'bids'},
        ),
    ]
